# Generated by Django 4.2.1 on 2023-06-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_newlisting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewListing',
            new_name='Listing',
        ),
    ]
